# Generated by Django 5.1.4 on 2025-01-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0003_customuser_delete_user'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
