# Generated by Django 5.1.4 on 2025-01-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0007_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
