# Generated by Django 5.1.4 on 2025-01-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0008_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=20)),
                ('brand_name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
