# Generated by Django 5.1.4 on 2025-02-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0009_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
