# Generated by Django 5.1.4 on 2025-02-15 06:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0011_cart_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_purchases', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.user')),
            ],
        ),
        migrations.CreateModel(
            name='Bargain',
            fields=[
                ('bargain_id', models.AutoField(primary_key=True, serialize=False)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.product')),
            ],
        ),
    ]
