# Generated by Django 5.1.4 on 2025-03-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0013_alter_customer_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserRadioWatch',
        ),
    ]
