# Generated by Django 5.1.4 on 2025-04-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0014_rename_user_userradiowatch'),
    ]

    operations = [
    ]
