# Generated by Django 5.1.4 on 2025-04-02 07:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0016_remove_userradiowatch_role_userradiowatch_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userradiowatch',
            name='total_purchases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userradiowatch',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='userradiowatch',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
