# Generated by Django 5.1.4 on 2025-04-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0017_userradiowatch_total_purchases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Bargain',
        ),
    ]
