# Generated by Django 5.1.4 on 2025-04-03 06:23

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0019_alter_purchasehistory_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.product'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.customer')),
            ],
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.order'),
            preserve_default=False,
        ),
    ]
