# Generated by Django 5.1.4 on 2025-04-03 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0021_alter_purchasehistory_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.order'),
        ),
    ]
