# Generated by Django 5.1.4 on 2025-04-03 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RadioWatch', '0022_alter_purchasehistory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='RadioWatch.product'),
            preserve_default=False,
        ),
    ]
